const defaultConfig = {
  countryList: [
    { label: '阿富汗', value: 'AF' },
    { label: '阿尔巴尼亚', value: 'AL' },
    { label: '安道尔', value: 'AD' },
    { label: '安哥拉', value: 'AO' },
    { label: '安圭拉', value: 'AI' },
    { label: '南极洲', value: 'AQ' },
    { label: '安提瓜和巴布达', value: 'AG' },
    { label: '阿根廷', value: 'AR' },
    { label: '亚美尼亚', value: 'AM' },
    { label: '阿鲁巴', value: 'AW' },
    { label: '澳大利亚', value: 'AU' },
    { label: '奥地利', value: 'AT' },
    { label: '阿塞拜疆', value: 'AZ' },
    { label: '阿联酋', value: 'AE' },
    { label: '巴哈马', value: 'BS' },
    { label: '巴林', value: 'BH' },
    { label: '孟加拉', value: 'BD' },
    { label: '巴巴多斯', value: 'BB' },
    { label: '白俄罗斯', value: 'BY' },
    { label: '伯利兹', value: 'BZ' },
    { label: '比利时', value: 'BE' },
    { label: '贝宁', value: 'BJ' },
    { label: '百慕大', value: 'BM' },
    { label: '不丹', value: 'BT' },
    { label: '玻利维亚', value: 'BO' },
    { label: '波黑', value: 'BA' },
    { label: '博茨瓦纳', value: 'BW' },
    { label: '布维岛', value: 'BV' },
    { label: '巴西', value: 'BR' },
    { label: '文莱', value: 'BN' },
    { label: '保加利亚', value: 'BG' },
    { label: '布其纳法索', value: 'BF' },
    { label: '布隆迪', value: 'BI' },
    { label: '喀麦隆', value: 'CM' },
    { label: '加拿大', value: 'CA' },
    { label: '佛得角', value: 'CV' },
    { label: '中非共和国', value: 'CF' },
    { label: '智利', value: 'CL' },
    { label: '中国', value: 'CN' },
    { label: '圣诞岛', value: 'CX' },
    { label: '可可岛', value: 'CC' },
    { label: '哥伦比亚', value: 'CO' },
    { label: '瑞士', value: 'CH' },
    { label: '刚果', value: 'CG' },
    { label: '库克群岛', value: 'CK' },
    { label: '哥斯达黎加', value: 'CR' },
    { label: '象牙海岸', value: 'CI' },
    { label: '古巴', value: 'CU' },
    { label: '塞浦路斯', value: 'CY' },
    { label: '捷克共和国', value: 'CZ' },
    { label: '丹麦', value: 'DK' },
    { label: '吉布提', value: 'DJ' },
    { label: '多明哥', value: 'DM' },
    { label: '德国', value: 'DE' },
    { label: '多米尼加', value: 'DO' },
    { label: '阿尔及利亚', value: 'DZ' },
    { label: '厄瓜多尔', value: 'EC' },
    { label: '埃及', value: 'EG' },
    { label: '西撒哈拉', value: 'EH' },
    { label: '西班牙', value: 'ES' },
    { label: '爱沙尼亚', value: 'EE' },
    { label: '埃塞俄比亚', value: 'ET' },
    { label: '斐济', value: 'FJ' },
    { label: '福克兰群岛', value: 'FK' },
    { label: '芬兰', value: 'FI' },
    { label: '法国', value: 'FR' },
    { label: '密克罗尼西亚', value: 'FM' },
    { label: '加蓬', value: 'GA' },
    { label: '赤道几内亚', value: 'GQ' },
    { label: '法属圭亚那', value: 'GF' },
    { label: '冈比亚', value: 'GM' },
    { label: '格鲁吉亚', value: 'GE' },
    { label: '加纳', value: 'GH' },
    { label: '直布罗陀', value: 'GI' },
    { label: '希腊', value: 'GR' },
    { label: '格陵兰', value: 'GL' },
    { label: '格林纳达', value: 'GD' },
    { label: '瓜德罗普', value: 'GP' },
    { label: '关岛', value: 'GU' },
    { label: '危地马拉', value: 'GT' },
    { label: '几内亚', value: 'GN' },
    { label: '几内亚比绍', value: 'GW' },
    { label: '圭亚那', value: 'GY' },
    { label: '克罗地亚', value: 'HR' },
    { label: '海地', value: 'HT' },
    { label: '洪都拉斯', value: 'HN' },
    { label: '匈牙利', value: 'HU' },
    { label: '冰岛', value: 'IS' },
    { label: '印度', value: 'IN' },
    { label: '印度尼西亚', value: 'ID' },
    { label: '伊朗', value: 'IR' },
    { label: '伊拉克', value: 'IQ' },
    { label: '英联邦的印度洋领域', value: 'IO' },
    { label: '爱尔兰', value: 'IE' },
    { label: '以色列', value: 'IL' },
    { label: '意大利', value: 'IT' },
    { label: '牙买加', value: 'JM' },
    { label: '日本', value: 'JP' },
    { label: '约旦', value: 'JO' },
    { label: '哈萨克斯坦', value: 'KZ' },
    { label: '肯尼亚', value: 'KE' },
    { label: '基里巴斯', value: 'KI' },
    { label: '朝鲜', value: 'KP' },
    { label: '韩国', value: 'KR' },
    { label: '柬埔寨', value: 'KH' },
    { label: '科摩罗', value: 'KM' },
    { label: '科威特', value: 'KW' },
    { label: '吉尔吉斯斯坦', value: 'KG' },
    { label: '开曼群岛', value: 'KY' },
    { label: '老挝', value: 'LA' },
    { label: '斯里兰卡', value: 'LK' },
    { label: '拉托维亚', value: 'LV' },
    { label: '黎巴嫩', value: 'LB' },
    { label: '莱索托', value: 'LS' },
    { label: '利比里亚', value: 'LR' },
    { label: '利比亚', value: 'LY' },
    { label: '列支敦士登', value: 'LI' },
    { label: '立陶宛', value: 'LT' },
    { label: '卢森堡', value: 'LU' },
    { label: '圣卢西亚', value: 'LC' },
    { label: '马达加斯加', value: 'MG' },
    { label: '马拉维', value: 'MW' },
    { label: '马来西亚', value: 'MY' },
    { label: '马尔代夫', value: 'MV' },
    { label: '马里', value: 'ML' },
    { label: '马尔他（马耳他）', value: 'MT' },
    { label: '马绍尔群岛', value: 'MH' },
    { label: '毛里塔尼亚', value: 'MR' },
    { label: '毛里求斯', value: 'MU' },
    { label: '墨西哥', value: 'MX' },
    { label: '摩尔多瓦', value: 'MD' },
    { label: '摩纳哥', value: 'MC' },
    { label: '蒙古', value: 'MN' },
    { label: '摩洛哥', value: 'MA' },
    { label: '莫桑比克', value: 'MZ' },
    { label: '缅甸　', value: 'MM' },
    { label: '纳米比亚', value: 'NA' },
    { label: '瑙鲁', value: 'NR' },
    { label: '尼泊尔', value: 'NP' },
    { label: '荷兰', value: 'NL' },
    { label: '新喀里多尼亚', value: 'NC' },
    { label: '新西兰', value: 'NZ' },
    { label: '尼加拉瓜', value: 'NI' },
    { label: '尼日尔', value: 'NE' },
    { label: '尼日利亚', value: 'NG' },
    { label: '纽埃', value: 'NU' },
    { label: '挪威', value: 'NO' },
    { label: '阿曼', value: 'OM' },
    { label: '巴基斯坦', value: 'PK' },
    { label: '法属玻里尼西亚', value: 'PF' },
    { label: '帕劳', value: 'PW' },
    { label: '巴拿马', value: 'PA' },
    { label: '巴布亚新几内亚', value: 'PG' },
    { label: '巴拉圭', value: 'PY' },
    { label: '秘鲁', value: 'PE' },
    { label: '菲律宾', value: 'PH' },
    { label: '皮特开恩群岛', value: 'PN' },
    { label: '波兰', value: 'PL' },
    { label: '葡萄牙', value: 'PT' },
    { label: '波多黎各（美）', value: 'PR' },
    { label: '卡塔尔', value: 'QA' },
    { label: '罗马尼亚', value: 'RO' },
    { label: '俄罗斯联邦', value: 'RU' },
    { label: '卢旺达', value: 'RW' },
    { label: '萨尔瓦多', value: 'SV' },
    { label: '圣赫勒那', value: 'SH' },
    { label: '圣马力诺', value: 'SM' },
    { label: '圣多美与普林西比', value: 'ST' },
    { label: '沙特阿拉伯', value: 'SA' },
    { label: '塞内加尔', value: 'SN' },
    { label: '塞舌尔', value: 'SC' },
    { label: '塞拉利昂', value: 'SL' },
    { label: '新加坡', value: 'SG' },
    { label: '斯洛伐克', value: 'SK' },
    { label: '斯洛文尼亚', value: 'SI' },
    { label: '所罗门群岛', value: 'SB' },
    { label: '索马里', value: 'SO' },
    { label: '苏丹', value: 'SD' },
    { label: '苏里南', value: 'SR' },
    { label: '斯威士兰', value: 'SZ' },
    { label: '瑞典', value: 'SE' },
    { label: '叙利亚', value: 'SY' },
    { label: '苏联(前)', value: 'SU' },
    { label: '乍得', value: 'TD' },
    { label: '法属南方领土', value: 'TF' },
    { label: '塔吉克斯坦', value: 'TJ' },
    { label: '坦桑尼亚', value: 'TZ' },
    { label: '泰国', value: 'TH' },
    { label: '多哥', value: 'TG' },
    { label: '托克劳', value: 'TK' },
    { label: '汤加', value: 'TO' },
    { label: '特立尼达和多巴哥', value: 'TT' },
    { label: '突尼斯', value: 'TN' },
    { label: '土尔其', value: 'TR' },
    { label: '东帝', value: 'TP' },
    { label: '土库曼斯坦', value: 'TM' },
    { label: '图瓦卢', value: 'TV' },
    { label: '乌干达', value: 'UG' },
    { label: '乌克兰', value: 'UA' },
    { label: '英国', value: 'UK' },
    { label: '美国', value: 'US' },
    { label: '美国边远小岛', value: 'UM' },
    { label: '乌拉圭', value: 'UY' },
    { label: '乌兹别克斯坦', value: 'UZ' },
    { label: '梵蒂冈（罗马教庭）', value: 'VA' },
    { label: '委内瑞拉', value: 'VE' },
    { label: '越南', value: 'VN' },
    { label: '不列颠岛(英)', value: 'VG' },
    { label: '不列颠岛(美)', value: 'VI' },
    { label: '西萨摩亚', value: 'WS' },
    { label: '也门', value: 'YE' },
    { label: '南斯拉夫', value: 'YU' },
    { label: '南非', value: 'ZA' },
    { label: '扎伊尔', value: 'ZR' },
    { label: '赞比亚', value: 'ZM' },
    { label: '津巴布韦', value: 'ZW' }
  ],
  continentList: [
    { label: '非洲', value: 'AF' },
    { label: '欧洲', value: 'EU' },
    { label: '亚洲', value: 'AS' },
    { label: '大洋洲', value: 'OC' },
    { label: '北美洲', value: 'NA' },
    { label: '南美洲', value: 'SA' },
    { label: '南极洲', value: 'AN' }
  ],
  supportMethod: [
    { label: 'GET', value: 'GET' },
    { label: 'POST', value: 'POST' },
    { label: 'PUT', value: 'PUT' },
    { label: 'DELETE', value: 'DELETE' },
    { label: 'OPTIONS', value: 'OPTIONS' },
    { label: 'PURGE', value: 'PURGE' },
    { label: 'HEAD', value: 'HEAD' },
    { label: 'PATCH', value: 'PATCH' }
  ],
  supportHttpVersion: [
    { label: 'HTTP/1.0', value: 'HTTP/1.0' },
    { label: 'HTTP/1.1', value: 'HTTP/1.1' },
    { label: 'HTTP/2', value: 'HTTP/2' }
  ]
}

import { defineStore } from 'pinia'
import type { LabelValue } from 'vc-material'

interface IConfig {
  countryList: LabelValue[]
  continentList: LabelValue[]
  supportMethod: LabelValue[]
  supportHttpVersion: LabelValue[]
}

const { MODE } = import.meta.env
const UPPER_MODE = MODE.toUpperCase()
export const useConfigStore = defineStore(
  `__VCLOUD__${UPPER_MODE}__STORE_CDN_CONFIG__`,
  () => {
    // const config = reactive<IConfig>({
    //   countryList: [],
    //   continentList: [],
    //   supportMethod: [],
    //   supportHttpVersion: []
    // })

    const config = reactive<IConfig>({ ...defaultConfig })

    function getConfig() {
      // TODO; unrealized
      // get_bootstrap().then(res => {
      //   config.countryList = (res as any).country?.map(item => {
      //     return { label: item.name!, value: item.code! }
      //   })!
      //   config.continentList = (res as any).continent?.map(item => {
      //     return { label: item.name!, value: item.code! }
      //   })!
      //   config.supportMethod = (res as any).request_method?.map(item => {
      //     return { label: item.toUpperCase(), value: item.toUpperCase() }
      //   })!
      //   config.supportHttpVersion = (res as any).http_version?.map(item => {
      //     return { label: item.toUpperCase(), value: item.toUpperCase() }
      //   })!
      //   console.log(JSON.stringify(config))
      // })
    }

    return { config, getConfig }
  },
  {
    persist: true
  }
)
